### PR TITLE
Initial release

### LINKED ISSUE #5: Free text answers, as well as single-line and multi-line textboxes
## Describe the solution you'd like
The Survey module only provides single-choice (radiobuttons) or multiple-choice answers. Free text answers (single- and multiple-line) should be addded.

### PR DESCRIPTION
**Pull request by MaiklT**
## Changes made
- C#
- DAL2
- Moved settings ("Vote tracking" and "Survey Results") to permissions ("Participate" and "View results") to allow more granular access
- Added setting "Survey Type" (Survey or Quiz)
- Added option to display closing date message
- Added option to add a consent checkbox
- Added option to use a Captcha
- Added honeybot to reduce spam submissions
- Added free text answers
- Questions and answers can be sorted by drag & drop
- Added charts using ChartJS
- Different chart type (bar, vertical bar, pie, doghnut) selectable for each question
- CSV export of results
- Added GUID to results to determine which answers come from the same user (even if this completely anonymous). That allows further reports using other tools, eg. how did different genders or age groups vote.
- etc.

## PR Template Checklist

- [x] Fixes Bugs
- [x] Feature solution
- [ ] Other

## Please mark which issue is solved

Close #5, #9, #17, #18, #19, #20

### CODE REVIEW

**Comment by MaiklT** [comment]
[Changes.pptx](https://github.com/DNNCommunity/DNN.Survey/files/3022974/Changes.pptx)

**Comment by MaiklT** [comment]
[DotNetNuke.Modules.Survey.09.00.00-rc5.pa.zip](https://github.com/DNNCommunity/DNN.Survey/files/3064589/DotNetNuke.Modules.Survey.09.00.00-rc5.pa.zip)
This is a working install package containing the debug assemblies. Please install the [DNN Extension Library for Chart.js v2.7.3](https://github.com/EngageSoftware/DNN-JavaScript-Libraries/releases/tag/chart.js_2.7.3) before.

**Comment by MaiklT** [comment]
# Database changes

# Tables

## Table Surveys

* Changed field OptionType to int use an Enum
    * RadioButton: old value 'R' -> new value 0
    * CheckBox: old value 'C' -> new value 1
    * new value 2 for textbox
* Changed the length of Question to nvarchar(max)
* Added RepeatDirection and RepeatColumns for Radiobuttons and Checkboxes
* Added NumberOfRows for text answers
* Added ChartType
* Added LastModifiedDate and ModifiedByUserID
* Added Index to ModuleID (Foreign Key)
* Added Index to ModuleID + ViewOrder

## Table SurveyOptions
* Changed the length of OptionName to nvarchar(max)
* Added a default value of 0 for Votes
* Added CreatedDate, CreatedByUserID, LastModifiedDate and LastModifiedByUserID
* Added index to SurveyID (Foreign Key)
* Added index to SurveyID + ViewOrder

## Table SurveyResults
* Added IPAddess field
* Added TextAnswer field
* Added anonymous pseudo User-GUID
* Added Index to SurveyOptionID (Foreign Key)

# Stored Procedures

## Stored Procedures Surveys
* Added Stored Procedures
    * Surveys_AddOrChange
    * Surveys_CsvExport
    * Surveys_HasVoted
    * Surveys_Sort
* Removed Stored Procedures
    * AddSurvey
    * DeleteSurvey
    * GetSurvey
    * GetSurveys
    * UpdateSurvey

## Stored Procedures SurveyOptions
* Added Stored Procedures
    * SurveyOptions_AddOrChange
* Removed Stored Procedures
    * AddSurveyOption
    * DeleteSurveyOption
    * GetSurveyOptions
    * UpdateSurveyOption

## Stored Procedures SurveyResult
* Added Stored Procedures
    * SurveyResults_Add
    * SurveyResults_Get
    * SurveyResults_GetAll
    * SurveyResultData_Delete

* Removed stored procedures
    * AddSurveyResult
    * AddSurveyResult_cookie
    * DeleteSurveyResultData
    * GetSurveyResultData

# Views

## Views Surveys
* Added Views
    * vSurveys_CsvExport

**Comment by MaiklT** [comment]
Please find documentation here for the moment: [https://dnn-survey.readme.io/](https://dnn-survey.readme.io/)

**Comment by valadas** [comment]
Merging this PR as is without extensive review because there is no original codebase and it will make it easier to submit a few other pull requests to fix the small stuff needed here...

**Pull request merged**
